//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveHelper.Example.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("665257690651-aji1ca6q48hc6vhqv2mob7u5j737g65r.apps.googleusercontent.com")]
        public string GoogleDriveClientId {
            get {
                return ((string)(this["GoogleDriveClientId"]));
            }
            set {
                this["GoogleDriveClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mZU6BdEO-9tWlWnUqwnDwxAe")]
        public string GoogleDriveClientSecret {
            get {
                return ((string)(this["GoogleDriveClientSecret"]));
            }
            set {
                this["GoogleDriveClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1/GYKwB4ZHkILaW8S-Jh9DrYlwvVYfQaBv1qQrgIbHKhI")]
        public string GoogleDriveRefreshToken {
            get {
                return ((string)(this["GoogleDriveRefreshToken"]));
            }
            set {
                this["GoogleDriveRefreshToken"] = value;
            }
        }
    }
}
